import { ApiProperty } from '@nestjs/swagger';
import { MatchStatus } from '@prisma/client';

export class MatchListItemDto {
  @ApiProperty()
  id!: number;

  @ApiProperty()
  userId!: number;

  @ApiProperty({ required: false, nullable: true })
  title?: string | null;

  @ApiProperty({ required: false, nullable: true })
  player1Name?: string | null;

  @ApiProperty({ required: false, nullable: true })
  player2Name?: string | null;

  @ApiProperty({ required: false, nullable: true, format: 'date-time' })
  eventDate?: Date | null;

  @ApiProperty({ required: false, nullable: true })
  location?: string | null;

  @ApiProperty({ required: false, nullable: true })
  description?: string | null;

  @ApiProperty()
  originalVideoUrl!: string;

  @ApiProperty({ enum: MatchStatus })
  status!: MatchStatus;

  @ApiProperty({ format: 'date-time' })
  createdAt!: Date;

  @ApiProperty({ format: 'date-time' })
  updatedAt!: Date;
}

export class MatchDetailDto extends MatchListItemDto {
  @ApiProperty({
    description: 'Tracking payload generated by worker (court/timeline).',
    required: false,
    type: Object,
  })
  tracking?: Record<string, unknown> | null;
}
